import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Brain, ChevronRight, FileText, FolderOpen, Globe2, LogOut, MemoryStick, Menu, Mic2, Monitor, Plus, Search, Send, Settings, Sparkles, X } from 'lucide-react'
import LiquidEther from './effects/LiquidEther.jsx'
import MagicRings from './effects/MagicRings.jsx'
import { Conversation, DEFAULT_API, Device, DocumentItem, Memory, Message, SalarApi } from './api'
import './styles.css'

type View = 'home'|'memory'|'documents'|'devices'|'settings'
const api = new SalarApi()

function Login({onDone}:{onDone:()=>void}) {
  const [email,setEmail]=useState('owner@salar.local'), [password,setPassword]=useState('ChangeMeImmediately!'), [error,setError]=useState('')
  async function submit(e:React.FormEvent){e.preventDefault();setError('');try{await api.login(email,password);onDone()}catch(err){setError((err as Error).message)}}
  return <main className="login"><div className="ether"><LiquidEther colors={['#5227FF','#FF9FFC','#B497CF']} autoDemo resolution={0.5}/></div><form onSubmit={submit} className="login-card"><div className="mark">S</div><p className="kicker">PRIVATE INTELLIGENCE</p><h1>Enter SALAR</h1><p>Your secure command layer across every device.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button>Connect <ChevronRight size={17}/></button><small>API · {api.baseUrl}</small></form></main>
}

function App(){
  const [ready,setReady]=useState(false), [authed,setAuthed]=useState(!!api.token), [view,setView]=useState<View>('home'), [live,setLive]=useState(false), [menu,setMenu]=useState(false)
  useEffect(()=>{const t=setTimeout(()=>setReady(true),1900);return()=>clearTimeout(t)},[])
  useEffect(()=>{
    const invoke=(window as any).__TAURI_INTERNALS__?.invoke
    if(!authed||!invoke)return
    let stopped=false, timer:number
    async function connect(){
      let token=localStorage.getItem('salar.deviceToken')
      if(!token){const device=await api.registerDevice(`SALAR Desktop · ${navigator.platform||'Windows'}`);token=device.token;localStorage.setItem('salar.deviceToken',token);localStorage.setItem('salar.deviceId',device.id)}
      async function poll(){if(stopped||!token)return;try{const command=await api.nextDeviceCommand(token);if(command){try{const data=await invoke('execute_device_command',{kind:command.kind,payload:command.payload});await api.completeDeviceCommand(command.id,token,{ok:true,detail:'Executed by SALAR Desktop',data})}catch(e){await api.completeDeviceCommand(command.id,token,{ok:false,detail:String(e)})}}}catch(e){console.warn(e)}finally{if(!stopped)timer=window.setTimeout(poll,1800)}}
      poll()
    }
    connect().catch(console.error);return()=>{stopped=true;clearTimeout(timer)}
  },[authed])
  if(!ready)return <div className="loader"><div className="strands"></div><p>SALAR</p><span>INITIALIZING PRIVATE INTELLIGENCE</span></div>
  if(!authed)return <Login onDone={()=>setAuthed(true)}/>
  if(live)return <Live onClose={()=>setLive(false)}/>
  const nav=[['home',Sparkles,'Intelligence'],['memory',MemoryStick,'Memory'],['documents',FileText,'Documents'],['devices',Monitor,'Devices'],['settings',Settings,'Settings']] as const
  return <div className="app-shell"><div className="ether"><LiquidEther colors={['#5227FF','#FF9FFC','#B497CF']} mouseForce={20} cursorSize={100} resolution={0.5} autoDemo autoSpeed={0.5} autoIntensity={2.2}/></div><header><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button><div className="brand"><div className="mark">S</div><div><b>SALAR</b><small>PERSONAL INTELLIGENCE</small></div></div><div className="online"><i/> SECURE LINK</div></header><aside className={menu?'open':''}>{nav.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMenu(false)}}><Icon size={18}/><span>{label}</span></button>)}<button className="logout" onClick={()=>{localStorage.removeItem('salar.token');location.reload()}}><LogOut size={18}/>Sign out</button></aside><section className="workspace">{view==='home'&&<Chat onLive={()=>setLive(true)}/>} {view==='memory'&&<Memories/>}{view==='documents'&&<Documents/>}{view==='devices'&&<Devices/>}{view==='settings'&&<SettingsPage/>}</section></div>
}

function Chat({onLive}:{onLive:()=>void}){
  const [conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); const end=useRef<HTMLDivElement>(null)
  useEffect(()=>{api.conversations().then(async cs=>{const c=cs[0]||await api.createConversation();setConversation(c); if(cs[0]){const d=await api.conversation(c.id);setMessages(d.messages||[])}}).catch(e=>setError(e.message))},[])
  useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages])
  async function send(){if(!input.trim()||!conversation||busy)return;const text=input;setInput('');setBusy(true);setError('');const optimistic:Message={id:'temp',role:'user',content:text,created_at:new Date().toISOString()};setMessages(m=>[...m,optimistic]);try{const r=await api.chat(conversation.id,text);setMessages(m=>[...m.filter(x=>x.id!=='temp'),r.user_message,r.assistant_message])}catch(e){setMessages(m=>m.filter(x=>x.id!=='temp'));setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="chat-view"><div className="hero"><p className="kicker">COORDINATED INTELLIGENCE</p><h1>{messages.length?'Command stream':'What shall we accomplish?'}</h1><p>SALAR routes each request through local intelligence, memory, documents, and your connected devices.</p></div><div className="messages">{messages.map(m=><article key={m.id} className={m.role}><span>{m.role==='assistant'?'S':'YOU'}</span><p>{m.content}</p></article>)}{busy&&<article className="assistant thinking"><span>S</span><p>Reasoning across your private context…</p></article>}<div ref={end}/></div>{error&&<div className="toast">{error}</div>}<div className="composer"><button className="live-control" onClick={onLive} title="Enter Live mode"><Mic2/></button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask, create, search, or control…" rows={1}/><button className="send-control" onClick={send} disabled={busy||!input.trim()} title="Send command"><Send/></button></div></div>
}

function Live({onClose}:{onClose:()=>void}){const [heard,setHeard]=useState('Listening for your command…'),[reply,setReply]=useState('');useEffect(()=>{let active=true,conversationId='';const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setHeard('Voice recognition is unavailable in this browser.');return}const r=new SR();r.continuous=true;r.interimResults=true;r.lang=navigator.language||'en-US';api.createConversation('Live session').then(c=>conversationId=c.id).catch(e=>setReply(e.message));r.onresult=async(e:any)=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal&&conversationId){setHeard(text);try{const result=await api.chat(conversationId,text);if(!active)return;setReply(result.assistant_message.content);speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(result.assistant_message.content))}catch(err){setReply((err as Error).message)}}else interim+=text}if(interim)setHeard(interim)};r.onerror=()=>setReply('Microphone permission is required.');r.start();return()=>{active=false;r.stop();speechSynthesis.cancel()}},[]);return <main className="live"><div className="rings"><MagicRings color="#fc42ff" colorTwo="#42fcff" ringCount={6} speed={1} attenuation={10} lineThickness={2} baseRadius={0.35} radiusStep={0.1} scaleRate={0.1} opacity={1} noiseAmount={0.1} ringGap={1.5} fadeIn={0.7} fadeOut={0.5}/></div><button className="close" onClick={onClose}><X/></button><div className="live-copy"><p className="kicker">LIVE MODE · CONTINUOUS</p><h1>SALAR is listening</h1><p>{heard}</p>{reply&&<blockquote>{reply}</blockquote>}<span>Final voice commands are processed continuously through your private backend.</span></div></main>}

function Memories(){const [items,setItems]=useState<Memory[]>([]);useEffect(()=>{api.memories().then(setItems)},[]);return <Page title="Memory" subtitle="Facts and decisions SALAR can carry forward."><div className="grid">{items.map(x=><Card key={x.id} icon={<Brain/>} title={x.title} text={x.content}/>) }<Card icon={<Plus/>} title="Add memory" text="Ask SALAR to remember something from any conversation."/></div></Page>}
function Documents(){const [items,setItems]=useState<DocumentItem[]>([]),input=useRef<HTMLInputElement>(null);useEffect(()=>{api.documents().then(setItems)},[]);async function add(file?:File){if(file){const d=await api.upload(file);setItems(x=>[d,...x])}}return <Page title="Knowledge" subtitle="Search PDFs, notes, source code, and project files."><button className="primary" onClick={()=>input.current?.click()}><Plus size={17}/> Index document</button><input ref={input} hidden type="file" onChange={e=>add(e.target.files?.[0])}/><div className="grid">{items.map(x=><Card key={x.id} icon={<FileText/>} title={x.filename} text={x.media_type}/>)}</div></Page>}
function Devices(){const [items,setItems]=useState<Device[]>([]),[url,setUrl]=useState('https://github.com'),[notice,setNotice]=useState('');useEffect(()=>{api.devices().then(setItems)},[]);async function send(){if(!items[0])return;try{await api.command(items[0].id,'open_url',{url});setNotice('Command queued securely for the desktop.')}catch(e){setNotice((e as Error).message)}}return <Page title="Connected devices" subtitle="Send permission-aware commands through the shared SALAR backend.">{items.length>0&&<div className="device-command"><label>Open a secure URL on {items[0].name}<input value={url} onChange={e=>setUrl(e.target.value)}/></label><button className="primary" onClick={send}>Send command <Send size={16}/></button>{notice&&<p>{notice}</p>}</div>}<div className="grid">{items.map(x=><Card key={x.id} icon={<Monitor/>} title={x.name} text={`${x.platform} · ${x.last_seen_at?'online recently':'registered'}`}/>) }{!items.length&&<Card icon={<Globe2/>} title="No desktop linked" text="Install SALAR Desktop, then register this PC after signing in."/>}</div></Page>}
function SettingsPage(){const [url,setUrl]=useState(localStorage.getItem('salar.apiUrl')||DEFAULT_API);return <Page title="Settings" subtitle="One secure backend for desktop, web, and mobile."><div className="settings-card"><label>Public API address<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://api.yourdomain.com"/></label><button className="primary" onClick={()=>{localStorage.setItem('salar.apiUrl',url);location.reload()}}>Save and reconnect</button><p>Use HTTPS. Never expose Ollama directly to the internet; SALAR keeps it behind the authenticated API.</p></div></Page>}
function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="page"><p className="kicker">SALAR WORKSPACE</p><h1>{title}</h1><p>{subtitle}</p>{children}</div>}
function Card({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="card"><div>{icon}</div><h3>{title}</h3><p>{text}</p></article>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
